project:
  type: website
  output-dir: "docs"
website:
  title: "Xách tay Pháp Đức Bỉ"
  navbar:
    left: 
      - text: Mỹ phẩm
        href: mypham.qmd
      - text: Nước hoa
        href: nuochoa.qmd
format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss

editor: visual

